version: '3.3'

services:
  frontend:
    container_name: fintech-front-end
    build:
      context: ./front-end
      dockerfile: dockerfile
    ports:
      - "3000:3000"  # 將容器內的 3000 埠映射到主機的 3000 埠
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=/api
      - REACT_APP_WS_URL=ws://140.115.54.36:3001/ws
    depends_on:
      - backend
    networks:
      - nginx_proxy
      - app-network

  backend:
    container_name: fintech-back-end
    build:
      context: ./back-end
      dockerfile: dockerfile
    ports:
      - "5000:5000"  # 將容器內的 5000 埠映射到主機的 5000 埠
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    volumes:
      - ./back-end:/app
    networks:
      - nginx_proxy
      - app-network

  # 定義網路
networks:
  nginx_proxy:
    external: true
  app-network:
    internal: true